// Generates the table of signal photons from the total measured signal spectrum
// Usage example - $ root -l -q 'SignalFractionTable.C(2082. 0. 21777)'
// Original author - Pawel Plesniak

void customErrorHandler(int level, Bool_t abort, const char* location, const char* message) {
    /*
        Description
            Define a custom error handler that won't print the stack trace but will print an error message and exit.
    */
    std::cerr << message << std::endl;
    if (level > kInfo)
        exit(1);
};

std::string doubleToString(double value, int sigFigs) {
    /*
        Description
            Converts a double to a string with a defined number of significant figures

        Arguments
            value - value to convert to string
            sigFigs - number of significant figures to use

        Variables
            out - output string stream used to convert 'value' to a std::string
    */
    std::ostringstream out;
    out << std::fixed << std::setprecision(sigFigs - 1) << value;
    return out.str();
};

void SignalFractionTable(double n347, double n844, double n1809) {
    /*
        Description
            Generates the table describing the number of signal photons measured in the STM energy range

        Arguments
            n347 - total number of measured photons 347 keV STM energy range (use value from plot generated by plotMWDResults.C)
            n844 - total number of measured photons 844 keV STM energy range (use value from plot generated by plotMWDResults.C)
            n1809 - total number of measured photons 1809 keV STM energy range (use value from plot generated by plotMWDResults.C)

        Variables
    */

    // Determine the total signal count uncertainties
    const double u347 = std::sqrt(n347);
    const double u844 = std::sqrt(n844);
    const double u1809 = std::sqrt(n1809);

    // Determine the normalized total signal count uncertainties
    const double uf347 = u347 / n347;
    const double uf844 = u844 / n844;
    const double uf1809 = u1809 / n1809;


    // Define the signal to total ratios
    const double st347  = 0.2712;
    const double st844  = 0.6987;
    const double st1809 = 0.6032;

    // Define the signal to total ratio uncertainties
    const double ust347  = 0.0541;
    const double ust844  = 0.2064;
    const double ust1809 = 0.0715;

    // Determine the normalized signal to total ratio uncertainties
    const double ufst347  = ust347  / st347;
    const double ufst844  = ust844  / st844;
    const double ufst1809 = ust1809 / st1809;


    // Determine the signal photon counts
    const double nSignal347  = n347  * st347;
    const double nSignal844  = n844  * st844;
    const double nSignal1809 = n1809 * st1809;

    // Determine the signal photon count uncertainties
    const double uSignal347  = nSignal347  * std::sqrt(std::pow(uf347, 2)  + std::pow(ufst347, 2));;
    const double uSignal844  = nSignal844  * std::sqrt(std::pow(uf844, 2)  + std::pow(ufst844, 2));;
    const double uSignal1809 = nSignal1809 * std::sqrt(std::pow(uf1809, 2) + std::pow(ufst1809, 2));;


    // Define the signal photon energy strings
    std::string e347  = "347 keV";
    std::string e844  = "844 keV";
    std::string e1809 = "1809 keV";

    // Define measured photon strings
    std::string t347 = doubleToString(n347, 1)  + " ± " + doubleToString(u347, 1);
    std::string t844 = doubleToString(n844, 1)  + " ± " + doubleToString(u844, 1);
    std::string t1809 = doubleToString(n1809, 1) + " ± " + doubleToString(u1809, 1);

    // Define signal to total ratio strings
    std::string ratio347  = doubleToString(st347, 5)  + " ± " + doubleToString(ust347, 5);
    std::string ratio844  = doubleToString(st844, 5)  + " ± " + doubleToString(ust844, 5);
    std::string ratio1809 = doubleToString(st1809, 5) + " ± " + doubleToString(ust1809, 5);

    // Define signal photon strings
    std::string sig347  = doubleToString(nSignal347, 1)  + " ± " + doubleToString(uSignal347, 1);
    std::string sig844  = doubleToString(nSignal844, 1)  + " ± " + doubleToString(uSignal844, 1);
    std::string sig1809 = doubleToString(nSignal1809, 1) + " ± " + doubleToString(uSignal1809, 1);


    // Define column widths
    const int titleWidth = 40, signalWidth = 30, fullWidth = titleWidth + signalWidth * 3;

    // Print the table
    std::string tableTitle = "Signal Photons Summary Table";
    std::cout << std::string(fullWidth, '=') << std::endl;
    std::cout << std::string((fullWidth - tableTitle.size())/2, ' ') << tableTitle << std::endl;
    std::cout << std::string(fullWidth, '=') << std::endl;
    std::cout << std::setw(titleWidth) << std::left << " " << std::setw(signalWidth) << std::left << e347 << std::setw(signalWidth) << std::left << e844 << std::setw(signalWidth) << std::left << e1809 << std::endl;
    std::cout << std::string(fullWidth, '-') << std::endl;
    std::cout << std::setw(titleWidth) << std::left << "Total Measured Photons: " <<  std::setw(signalWidth) << std::left << t347 << std::setw(signalWidth) << std::left << t844 << std::setw(signalWidth) << std::left << t1809 << std::endl;
    std::cout << std::setw(titleWidth) << std::left << "Signal to Total ratio: " << std::setw(signalWidth) << std::left << ratio347 << std::setw(signalWidth) << std::left << ratio844 << std::setw(signalWidth) << std::left << ratio1809 << std::endl;
    std::cout << std::string(fullWidth, '-') << std::endl;
    std::cout << std::setw(titleWidth) << std::left << "Signal Photons: " << std::setw(signalWidth) << std::left << sig347 << std::setw(signalWidth) << std::left << sig844 << std::setw(signalWidth) << std::left << sig1809 << std::endl;
    std::cout << std::string(fullWidth, '=') << std::endl;

    return;
};